name: Environment Variable - Secrets

on: workflow_dispatch

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Access Secrets
        run: |
          echo "REACT_APP_MOUNTAIN_KEY : ${{ secrets.REACT_APP_MOUNTAIN_KEY }}"
