name: secret-key

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pull Repo
      - uses: actions/checkout@v3

      # Github Secrets에서 API Key 받아온 후 .env 파일에 추가
      - run: |
          echo "REACT_APP_MOUNTAIN_KEY=${{secrets.REACT_APP_MOUNTAIN_KEY}}" >> .env
      - run: cat .env
      - run: npm install
      - run: npm run build
